services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 6606
      MYSQL_DATABASE: sdp_db
      # MYSQL_USER: klu
      # MYSQL_PASSWORD: klu
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql   # volume added here

  backend:
    container_name: springboot
    build:
      context: ./sdp-backend
      dockerfile: ./backend.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    container_name: react
    build:
      context: ./sdp-frontend
      dockerfile: ./frontend.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql-data: